#!/usr/bin/env node
/**
 * DKG Context Sync — Injects DKG memory into CLAUDE.md.
 *
 * Called by Claude Code hooks (SessionStart, Stop) to keep CLAUDE.md
 * in sync with DKG Working Memory. Uses <dkg-context> tags to preserve
 * user content outside the managed section.
 *
 * Usage:
 *   dkg-claude-sync                    # Sync to ./CLAUDE.md
 *   dkg-claude-sync /path/to/project   # Sync to specific project
 *   dkg-claude-sync --observation "tool result text"  # Capture observation
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { DkgDaemonClient } from './dkg-client.js';

const OPEN_TAG = '<dkg-context>';
const CLOSE_TAG = '</dkg-context>';
const AGENT_NAME = process.env.DKG_AGENT_NAME ?? 'claude';
const DAEMON_URL = process.env.DKG_DAEMON_URL ?? 'http://127.0.0.1:9200';
const CONTEXT_GRAPH = process.env.DKG_CONTEXT_GRAPH ?? '';

// ─── Main ────────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const mode = args.includes('--observation') ? 'observation' : 'sync';

if (mode === 'observation') {
  // Capture a tool observation → send to daemon for entity extraction
  const obsIdx = args.indexOf('--observation');
  const text = args[obsIdx + 1] ?? '';
  if (text) {
    await captureObservation(text);
  }
} else {
  // Full context sync → query DKG → update CLAUDE.md
  const projectDir = args[0] ?? process.cwd();
  await syncContext(projectDir);
}

// ─── Context Sync ────────────────────────────────────────────────────────────

async function syncContext(projectDir: string): Promise<void> {
  const client = new DkgDaemonClient(DAEMON_URL);

  if (!(await client.healthCheck())) {
    // Daemon down — leave CLAUDE.md as-is (offline fallback)
    process.stderr.write('[dkg-sync] Daemon unreachable — skipping sync\n');
    return;
  }

  // Query agent's working memory for persistent facts
  let memoryBlock = '';
  try {
    const sparql = `SELECT ?content WHERE { ?s <urn:hermes:content> ?content }`;
    const result = await client.post('/api/query', {
      sparql,
      contextGraphId: CONTEXT_GRAPH || undefined,
    });
    const bindings = result?.results?.bindings ?? result?.result?.bindings ?? [];
    if (bindings.length > 0) {
      const facts = bindings.map((b: any) => {
        const v = b.content?.value ?? (typeof b.content === 'string' ? b.content : '');
        return v.replace(/^"(.*)"$/, '$1');
      }).filter(Boolean);

      if (facts.length > 0) {
        memoryBlock = '## Memory [DKG Working Memory]\n\n' + facts.join('\n\n');
      }
    }
  } catch (e) {
    process.stderr.write(`[dkg-sync] Memory query failed: ${e}\n`);
  }

  // Query node status for context
  let statusBlock = '';
  try {
    const status = await client.get('/api/status');
    const peers = status.connectedPeers ?? status.peers ?? 0;
    statusBlock = `## DKG Node\n\n` +
      `- Status: connected\n` +
      `- Peers: ${peers}\n` +
      `- Context Graph: ${CONTEXT_GRAPH || '(default)'}\n` +
      `- Agent: ${AGENT_NAME}`;
  } catch {
    statusBlock = '## DKG Node\n\n- Status: connected (details unavailable)';
  }

  // Build the full DKG context block
  const toolsBlock = `## DKG Tools

MEMORY: dkg_memory (store facts), dkg_query (SPARQL search)
COLLABORATE: dkg_share (team), dkg_publish (chain, costs TRAC), dkg_wallet_balances
NETWORK: dkg_find_agents, dkg_send_message, dkg_read_messages, dkg_invoke_skill
PROJECTS: dkg_context_graph_create, dkg_subscribe, dkg_status

TRUST FLOW: Working Memory (free) → SHARE → Shared Memory (free) → PUBLISH → Verified Memory (TRAC)`;

  const contextContent = [
    '<!-- Auto-generated by DKG adapter. Content between these tags is managed. -->',
    '',
    statusBlock,
    '',
    memoryBlock || '## Memory [DKG Working Memory]\n\n(No facts stored yet. Use dkg_memory to persist important facts.)',
    '',
    toolsBlock,
  ].join('\n');

  // Inject into CLAUDE.md
  const claudeMdPath = join(projectDir, 'CLAUDE.md');
  injectContext(claudeMdPath, contextContent);

  process.stderr.write(`[dkg-sync] Updated ${claudeMdPath}\n`);
}

// ─── Observation Capture ─────────────────────────────────────────────────────

async function captureObservation(text: string): Promise<void> {
  const client = new DkgDaemonClient(DAEMON_URL);
  if (!(await client.healthCheck())) return;

  try {
    await client.post('/api/hermes/session-turn', {
      sessionId: `claude-${Date.now()}`,
      user: '',
      assistant: text.slice(0, 2000),
      agentName: AGENT_NAME,
    });
  } catch (e) {
    process.stderr.write(`[dkg-sync] Observation capture failed: ${e}\n`);
  }
}

// ─── Context Injection ───────────────────────────────────────────────────────

function injectContext(filePath: string, content: string): void {
  const wrapped = `${OPEN_TAG}\n${content}\n${CLOSE_TAG}`;

  const dir = dirname(filePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  if (existsSync(filePath)) {
    let existing = readFileSync(filePath, 'utf-8');

    const startIdx = existing.indexOf(OPEN_TAG);
    const endIdx = existing.indexOf(CLOSE_TAG);

    if (startIdx !== -1 && endIdx !== -1) {
      // Replace existing tagged section
      existing = existing.slice(0, startIdx) + wrapped + existing.slice(endIdx + CLOSE_TAG.length);
    } else {
      // Append tagged section
      existing = existing.trimEnd() + '\n\n' + wrapped + '\n';
    }

    writeFileSync(filePath, existing, 'utf-8');
  } else {
    // Create new file
    writeFileSync(filePath, wrapped + '\n', 'utf-8');
  }
}
